# === PoTranslatorByHAN · Python HTTP 桥接 ===
# 提供 WorkerThreadPool 后台线程入口
# Python 脚本内嵌在 EMBEDDED_PY_B64 常量中，导出后无需外部文件
# 注意：使用的谷歌翻译接口为非官方 API，仅供学习研究使用，不可用于商业用途
class_name PythonHttpBridge
extends RefCounted

const PY_SCRIPT_PATH = "res://Main/Translate/translate_full.py.txt"

static var _running_pid: int = -1
static var _cancel_flag: bool = false

## 内嵌 Python 脚本（Base64），优先读文件，兜底用此常量
const EMBEDDED_PY_B64 = "aW1wb3J0IGpzb24sIHN5cywgdXJsbGliLnJlcXVlc3QsIHVybGxpYi5lcnJvciwgdXJsbGliLnBhcnNlLCB0cmFjZWJhY2ssIG9zLCB6aXBmaWxlLCB4bWwuZXRyZWUuRWxlbWVudFRyZWUgYXMgRVQsIHJlCgpwb19wYXRoICAgICAgID0gc3lzLmFyZ3ZbMV0Kc3JjX2xhbmcgICAgICA9IHN5cy5hcmd2WzJdCnRhcmdldF9sYW5nICAgPSBzeXMuYXJndlszXQpiYXRjaF9zaXplICAgID0gaW50KHN5cy5hcmd2WzRdKQpwcm9ncmVzc19wYXRoID0gc3lzLmFyZ3ZbNV0KcHJvamVjdF9wYXRoICA9IHN5cy5hcmd2WzZdIGlmIGxlbihzeXMuYXJndikgPiA2IGVsc2UgIiIKCnJlc3VsdF9wYXRoID0gcHJvZ3Jlc3NfcGF0aC5yZXBsYWNlKCJfdHJhbnNsYXRlX3Byb2dyZXNzLmpzb24iLCAiX3RyYW5zbGF0ZV9yZXN1bHQuanNvbiIpCmxvZ19wYXRoICAgID0gcHJvZ3Jlc3NfcGF0aC5yZXBsYWNlKCJfdHJhbnNsYXRlX3Byb2dyZXNzLmpzb24iLCAiX3RyYW5zbGF0ZV9kZWJ1Zy5sb2ciKQoKZGVmIGxvZyhtc2cpOgogICAgdHJ5OgogICAgICAgIHdpdGggb3Blbihsb2dfcGF0aCwgImEiLCBlbmNvZGluZz0idXRmLTgiKSBhcyBsZjoKICAgICAgICAgICAgbGYud3JpdGUobXNnICsgIlxuIikKICAgIGV4Y2VwdDoKICAgICAgICBwYXNzCgpsb2coIj09PSB0cmFuc2xhdGVfZnVsbC5weSBzdGFydGVkID09PSIpCmxvZygicG9fcGF0aD0lcyIgJSBwb19wYXRoKQpsb2coInByb2plY3RfcGF0aD0lcyIgJSBwcm9qZWN0X3BhdGgpCgpFTkRQT0lOVCA9ICJodHRwczovL3RyYW5zbGF0ZS5nb29nbGVhcGlzLmNvbS90cmFuc2xhdGVfYS9zaW5nbGUiClRJTUVPVVQgID0gMTUKSERSICAgICAgPSB7IlVzZXItQWdlbnQiOiAiTW96aWxsYS81LjAifQoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KIyAgUE8g6Kej5p6QIC8g5YaZ5YWl77yI5ZCM5LmL5YmN77yJCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CgpkZWYgc3RyaXBfcG9fc3RyaW5nKHMpOgogICAgdCA9IHMuc3RyaXAoKQogICAgaWYgdC5zdGFydHN3aXRoKCciJykgYW5kIHQuZW5kc3dpdGgoJyInKToKICAgICAgICB0ID0gdFsxOi0xXQogICAgcmV0dXJuIHQucmVwbGFjZSgiXFxuIiwiXG4iKS5yZXBsYWNlKCJcXHQiLCJcdCIpLnJlcGxhY2UoJ1xcIicsJyInKS5yZXBsYWNlKCJcXFxcIiwiXFwiKQoKZGVmIGVzY2FwZV9wbyhzKToKICAgIHJldHVybiBzLnJlcGxhY2UoIlxcIiwiXFxcXCIpLnJlcGxhY2UoJyInLCdcXCInKS5yZXBsYWNlKCJcbiIsIlxcbiIpLnJlcGxhY2UoIlx0IiwiXFx0IikKCmRlZiBwb19xdW90ZShzKToKICAgIHJldHVybiAnIicrZXNjYXBlX3BvKHMpKyciJwoKZGVmIHJlYWRfY29udGludWF0aW9uKGYpOgogICAgcmVzdWx0PSIiCiAgICB3aGlsZSBUcnVlOgogICAgICAgIHBvcz1mLnRlbGwoKTsgbGluZT1mLnJlYWRsaW5lKCkKICAgICAgICBpZiBub3QgbGluZTogYnJlYWsKICAgICAgICBzPWxpbmUuc3RyaXAoKQogICAgICAgIGlmIHMuc3RhcnRzd2l0aCgnIicpOiByZXN1bHQrPXN0cmlwX3BvX3N0cmluZyhzKQogICAgICAgIGVsc2U6IGYuc2Vlayhwb3MpOyBicmVhawogICAgcmV0dXJuIHJlc3VsdAoKZGVmIHBhcnNlX3BvKGZpbGVfcGF0aCk6CiAgICBlbnRyaWVzPVtdOyBoZWFkZXI9IiI7IGNvbnRleHRzPVtdICAjIGNvbnRleHRzOiDmr4/kuKrmnaHnm67nmoQgIzog5rOo6YeK6KGM5YaF5a6577yI55So5LqO6K+t5aKD5Yy56YWN77yJCiAgICB3aXRoIG9wZW4oZmlsZV9wYXRoLCJyIixlbmNvZGluZz0idXRmLTgiKSBhcyBmOiByYXc9Zi5yZWFkKCkKICAgIGZpcnN0PXJhdy5maW5kKCJcbm1zZ2N0eHQgIikKICAgIGlmIGZpcnN0PT0tMTogZmlyc3Q9cmF3LmZpbmQoIlxubXNnaWQgIikKICAgIGlmIGZpcnN0PjA6IGhlYWRlcj1yYXdbOmZpcnN0KzFdCiAgICBlbGlmIGZpcnN0PT0tMTogaGVhZGVyPXJhdwogICAgaW5faGVhZGVyPVRydWU7IGN1cl9jdHg9Y3VyX21zZ2lkPWN1cl9tc2dzdHI9IiI7IGN1cl9jdHh4PSIiCiAgICBjb2xsZWN0aW5nX21zZ2lkPWNvbGxlY3RpbmdfbXNnc3RyPUZhbHNlCiAgICB3aXRoIG9wZW4oZmlsZV9wYXRoLCJyIixlbmNvZGluZz0idXRmLTgiKSBhcyBmOgogICAgICAgIHdoaWxlIFRydWU6CiAgICAgICAgICAgIGxpbmU9Zi5yZWFkbGluZSgpCiAgICAgICAgICAgIGlmIG5vdCBsaW5lOiBicmVhawogICAgICAgICAgICBpZiBsaW5lLnN0YXJ0c3dpdGgoIiM6Iik6CiAgICAgICAgICAgICAgICBjdXJfY3R4eCArPSBsaW5lLnN0cmlwKCkgKyAiXG4iCiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICBpZiBsaW5lLnN0YXJ0c3dpdGgoIiMiKTogY29udGludWUKICAgICAgICAgICAgaWYgbGluZS5zdGFydHN3aXRoKCJtc2djdHh0ICIpOgogICAgICAgICAgICAgICAgaWYgbm90IGluX2hlYWRlciBhbmQgY3VyX21zZ2lkIT0iIjoKICAgICAgICAgICAgICAgICAgICBlbnRyaWVzLmFwcGVuZCgoY3VyX2N0eCxjdXJfbXNnaWQsY3VyX21zZ3N0cikpOyBjb250ZXh0cy5hcHBlbmQoY3VyX2N0eHgpOyBjdXJfY3R4eD0iIgogICAgICAgICAgICAgICAgY3VyX2N0eD1zdHJpcF9wb19zdHJpbmcobGluZVs4Ol0pOyBjb2xsZWN0aW5nX21zZ2lkPWNvbGxlY3RpbmdfbXNnc3RyPUZhbHNlCiAgICAgICAgICAgIGVsaWYgbGluZS5zdGFydHN3aXRoKCJtc2dpZCAiKToKICAgICAgICAgICAgICAgIHZhbD1zdHJpcF9wb19zdHJpbmcobGluZVs2Ol0pCiAgICAgICAgICAgICAgICBpZiBpbl9oZWFkZXIgYW5kIHZhbD09IiI6CiAgICAgICAgICAgICAgICAgICAgd2hpbGUgVHJ1ZToKICAgICAgICAgICAgICAgICAgICAgICAgbGw9Zi5yZWFkbGluZSgpCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIG5vdCBsbCBvciBub3QgKGxsLnN0cmlwKCkuc3RhcnRzd2l0aCgnIicpIGFuZCBsbC5zdHJpcCgpIT0nIiInKTogYnJlYWsKICAgICAgICAgICAgICAgICAgICBpbl9oZWFkZXI9RmFsc2U7IGNvbnRpbnVlCiAgICAgICAgICAgICAgICBpbl9oZWFkZXI9RmFsc2U7IGN1cl9tc2dpZD12YWwrcmVhZF9jb250aW51YXRpb24oZikKICAgICAgICAgICAgICAgIGNvbGxlY3RpbmdfbXNnaWQ9VHJ1ZTsgY29sbGVjdGluZ19tc2dzdHI9RmFsc2UKICAgICAgICAgICAgZWxpZiBsaW5lLnN0YXJ0c3dpdGgoIm1zZ3N0ciAiKToKICAgICAgICAgICAgICAgIGN1cl9tc2dzdHI9c3RyaXBfcG9fc3RyaW5nKGxpbmVbNzpdKStyZWFkX2NvbnRpbnVhdGlvbihmKQogICAgICAgICAgICAgICAgY29sbGVjdGluZ19tc2dpZD1GYWxzZTsgY29sbGVjdGluZ19tc2dzdHI9VHJ1ZQogICAgICAgICAgICBlbGlmIGxpbmUuc3RyaXAoKS5zdGFydHN3aXRoKCciJyk6CiAgICAgICAgICAgICAgICBjb250PXN0cmlwX3BvX3N0cmluZyhsaW5lKQogICAgICAgICAgICAgICAgaWYgY29sbGVjdGluZ19tc2dpZDogY3VyX21zZ2lkKz1jb250CiAgICAgICAgICAgICAgICBlbGlmIGNvbGxlY3RpbmdfbXNnc3RyOiBjdXJfbXNnc3RyKz1jb250CiAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICBpZiBub3QgaW5faGVhZGVyIGFuZCBjb2xsZWN0aW5nX21zZ3N0cjoKICAgICAgICAgICAgICAgICAgICBlbnRyaWVzLmFwcGVuZCgoY3VyX2N0eCxjdXJfbXNnaWQsY3VyX21zZ3N0cikpOyBjb250ZXh0cy5hcHBlbmQoY3VyX2N0eHgpCiAgICAgICAgICAgICAgICAgICAgY3VyX21zZ2lkPSIiOyBjdXJfY3R4eD0iIgogICAgICAgICAgICAgICAgY29sbGVjdGluZ19tc2dpZD1jb2xsZWN0aW5nX21zZ3N0cj1GYWxzZQogICAgaWYgbm90IGluX2hlYWRlciBhbmQgY29sbGVjdGluZ19tc2dzdHIgYW5kIGN1cl9tc2dpZCE9IiI6CiAgICAgICAgZW50cmllcy5hcHBlbmQoKGN1cl9jdHgsY3VyX21zZ2lkLGN1cl9tc2dzdHIpKTsgY29udGV4dHMuYXBwZW5kKGN1cl9jdHh4KQogICAgcmV0dXJuIGVudHJpZXMsaGVhZGVyLGNvbnRleHRzCgpkZWYgX2ZpbmRfbGluZV9lbmQocmF3LHBvcyk6CiAgICBubD1yYXcuZmluZCgiXG4iLHBvcyk7IHJldHVybiBsZW4ocmF3KSBpZiBubD09LTEgZWxzZSBubCsxCgpkZWYgX2J1aWxkX3BvX2VudHJ5KHByZWZpeCx0ZXh0KToKICAgIGlmIHRleHQ9PSIiOiByZXR1cm4gcHJlZml4KycgIiJcbicKICAgIHRvaz10ZXh0LnNwbGl0KCJcbiIpCiAgICBpZiBsZW4odG9rKTw9MTogcmV0dXJuIHByZWZpeCsiICIrcG9fcXVvdGUodGV4dCkrIlxuIgogICAgcj1wcmVmaXgrIiAiK3BvX3F1b3RlKHRva1swXSkrIlxuIgogICAgZm9yIHQgaW4gdG9rWzE6XTogcis9JyInK2VzY2FwZV9wbyh0KSsnIlxuJwogICAgcmV0dXJuIHIKCmRlZiByZXBsYWNlX21zZ3N0cl9pbnBsYWNlKGZpbGVfcGF0aCxlbnRyaWVzLGhlYWRlcik6CiAgICB3aXRoIG9wZW4oZmlsZV9wYXRoLCJyIixlbmNvZGluZz0idXRmLTgiKSBhcyBmOiByYXc9Zi5yZWFkKCkKICAgIHJlc3VsdD1oZWFkZXI7IHNjYW5fcG9zPWxlbihoZWFkZXIpLTEKICAgIGZvciBjdHgsbWlkLG1zdHIgaW4gZW50cmllczoKICAgICAgICBpZiBub3QgbWlkOiBjb250aW51ZQogICAgICAgIG1pZF9wb3M9cmF3LmZpbmQoIlxubXNnaWQgIixzY2FuX3BvcykKICAgICAgICBpZiBtaWRfcG9zPT0tMTogYnJlYWsKICAgICAgICBtaWRfcG9zKz0xOyByZXN1bHQrPXJhd1tzY2FuX3BvczptaWRfcG9zXQogICAgICAgIG1pZF9lbmQ9X2ZpbmRfbGluZV9lbmQocmF3LG1pZF9wb3MpOyBtaWRfbmV4dD1taWRfZW5kCiAgICAgICAgd2hpbGUgbWlkX25leHQ8bGVuKHJhdyk6CiAgICAgICAgICAgIG5sPXJhdy5maW5kKCJcbiIsbWlkX25leHQpCiAgICAgICAgICAgIGlmIG5sPT0tMTogbmw9bGVuKHJhdykKICAgICAgICAgICAgaWYgcmF3W21pZF9uZXh0Om5sXS5zdHJpcCgpLnN0YXJ0c3dpdGgoJyInKTogbWlkX25leHQ9bmwrMQogICAgICAgICAgICBlbHNlOiBicmVhawogICAgICAgIG1pZF9vbGQ9cmF3W21pZF9wb3M6bWlkX25leHRdCiAgICAgICAgbXN0cl9wb3M9cmF3LmZpbmQoIm1zZ3N0ciAiLG1pZF9uZXh0KQogICAgICAgIGlmIG1zdHJfcG9zPT0tMSBvciBtc3RyX3Bvcz49bGVuKHJhdyk6IHJlc3VsdCs9cmF3W21pZF9wb3M6XTsgYnJlYWsKICAgICAgICBtc3RyX2VuZD1fZmluZF9saW5lX2VuZChyYXcsbXN0cl9wb3MpOyBtc3RyX25leHQ9bXN0cl9lbmQKICAgICAgICB3aGlsZSBtc3RyX25leHQ8bGVuKHJhdyk6CiAgICAgICAgICAgIG5sPXJhdy5maW5kKCJcbiIsbXN0cl9uZXh0KQogICAgICAgICAgICBpZiBubD09LTE6IG5sPWxlbihyYXcpCiAgICAgICAgICAgIGlmIHJhd1ttc3RyX25leHQ6bmxdLnN0cmlwKCkuc3RhcnRzd2l0aCgnIicpOiBtc3RyX25leHQ9bmwrMQogICAgICAgICAgICBlbHNlOiBicmVhawogICAgICAgIHJlc3VsdCs9bWlkX29sZDsgcmVzdWx0Kz1fYnVpbGRfcG9fZW50cnkoIm1zZ3N0ciIsbXN0cik7IHNjYW5fcG9zPW1zdHJfbmV4dAogICAgaWYgc2Nhbl9wb3M8bGVuKHJhdyk6IHJlc3VsdCs9cmF3W3NjYW5fcG9zOl0KICAgIHdpdGggb3BlbihmaWxlX3BhdGgsInciLGVuY29kaW5nPSJ1dGYtOCIsbmV3bGluZT0iIikgYXMgZjogZi53cml0ZShyZXN1bHQpCgoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KIyAgWExTWCDop4TliJnliqDovb3vvJo2IOenjeinhOWImeexu+WeiwojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKZGVmIF9yZWFkX3NoYXJlZF9zdHJpbmdzKHpmKToKICAgICIiIuivu+WPliB4bC9zaGFyZWRTdHJpbmdzLnhtbO+8jOi/lOWbnuWtl+espuS4suWIl+ihqCIiIgogICAgc3NfZmlsZSA9ICd4bC9zaGFyZWRTdHJpbmdzLnhtbCcKICAgIGlmIHNzX2ZpbGUgbm90IGluIHpmLm5hbWVsaXN0KCk6CiAgICAgICAgcmV0dXJuIFtdCiAgICB4bWxfc3RyID0gemYucmVhZChzc19maWxlKS5kZWNvZGUoJ3V0Zi04JykKICAgIHJvb3QgPSBFVC5mcm9tc3RyaW5nKHhtbF9zdHIpCiAgICBucyA9IHsncyc6ICdodHRwOi8vc2NoZW1hcy5vcGVueG1sZm9ybWF0cy5vcmcvc3ByZWFkc2hlZXRtbC8yMDA2L21haW4nfQogICAgc3RyaW5ncyA9IFtdCiAgICBmb3Igc2kgaW4gcm9vdC5maW5kYWxsKCcuLy9zOnNpJywgbnMpOgogICAgICAgIHRfZWwgPSBzaS5maW5kKCcuLy9zOnQnLCBucykKICAgICAgICB2YWwgPSAiIgogICAgICAgIGlmIHRfZWwgaXMgbm90IE5vbmU6CiAgICAgICAgICAgICMg5a+M5paH5pysIDxyPjx0Pi4uLjwvdD48L3I+77yM6ZyA6KaB5ou85o6lCiAgICAgICAgICAgIHRleHRzID0gc2kuZmluZGFsbCgnLi8vczp0JywgbnMpCiAgICAgICAgICAgIHZhbCA9ICIiLmpvaW4odC50ZXh0IG9yICIiIGZvciB0IGluIHRleHRzKQogICAgICAgIHN0cmluZ3MuYXBwZW5kKHZhbCkKICAgIHJldHVybiBzdHJpbmdzCgoKZGVmIF9yZWFkX3hsc3hfc2hlZXQoemYsIHNoZWV0X2ZpbGUsIHNoYXJlZF9zdHJpbmdzKToKICAgICIiIuivu+WPluS4gOS4qiBzaGVldO+8jOi/lOWbniBbe2NvbF9sZXR0ZXI6IHZhbHVlfSwgLi4uXSIiIgogICAgaWYgc2hlZXRfZmlsZSBub3QgaW4gemYubmFtZWxpc3QoKToKICAgICAgICByZXR1cm4gW10KICAgIHhtbF9zdHIgPSB6Zi5yZWFkKHNoZWV0X2ZpbGUpLmRlY29kZSgndXRmLTgnKQogICAgcm9vdCA9IEVULmZyb21zdHJpbmcoeG1sX3N0cikKICAgIG5zID0geydzJzogJ2h0dHA6Ly9zY2hlbWFzLm9wZW54bWxmb3JtYXRzLm9yZy9zcHJlYWRzaGVldG1sLzIwMDYvbWFpbid9CiAgICByb3dzID0gW10KICAgIGZvciByb3cgaW4gcm9vdC5maW5kYWxsKCcuLy9zOnJvdycsIG5zKToKICAgICAgICBjZWxscyA9IHt9CiAgICAgICAgZm9yIGMgaW4gcm93LmZpbmRhbGwoJ3M6YycsIG5zKToKICAgICAgICAgICAgcmVmID0gYy5nZXQoJ3InLCAnJykKICAgICAgICAgICAgY29sID0gcmVmLnJzdHJpcCgnMDEyMzQ1Njc4OScpCiAgICAgICAgICAgIHZhbCA9ICIiCiAgICAgICAgICAgIHQgPSBjLmdldCgndCcsICcnKQogICAgICAgICAgICBpZiB0ID09ICdzJzoKICAgICAgICAgICAgICAgICMgc2hhcmVkIHN0cmluZ++8mnYg5Lit5piv57Si5byV5Y+3CiAgICAgICAgICAgICAgICB2ID0gYy5maW5kKCdzOnYnLCBucykKICAgICAgICAgICAgICAgIGlmIHYgaXMgbm90IE5vbmUgYW5kIHYudGV4dDoKICAgICAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgICAgIGlkeCA9IGludCh2LnRleHQpCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIDAgPD0gaWR4IDwgbGVuKHNoYXJlZF9zdHJpbmdzKToKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHZhbCA9IHNoYXJlZF9zdHJpbmdzW2lkeF0KICAgICAgICAgICAgICAgICAgICBleGNlcHQgVmFsdWVFcnJvcjoKICAgICAgICAgICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICBlbGlmIHQgaW4gKCdpbmxpbmVTdHInLCAnc3RyJyk6CiAgICAgICAgICAgICAgICAjIGlubGluZSBzdHJpbmcKICAgICAgICAgICAgICAgIGlzX2VsID0gYy5maW5kKCdzOmlzJywgbnMpCiAgICAgICAgICAgICAgICBpZiBpc19lbCBpcyBub3QgTm9uZToKICAgICAgICAgICAgICAgICAgICB0X2VsID0gaXNfZWwuZmluZCgnczp0JywgbnMpCiAgICAgICAgICAgICAgICAgICAgaWYgdF9lbCBpcyBub3QgTm9uZSBhbmQgdF9lbC50ZXh0OgogICAgICAgICAgICAgICAgICAgICAgICB2YWwgPSB0X2VsLnRleHQKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgICMg5pWw5YC844CB5biD5bCU562J55u05o6l5Y+WIHYg5paH5pysCiAgICAgICAgICAgICAgICB2ID0gYy5maW5kKCdzOnYnLCBucykKICAgICAgICAgICAgICAgIGlmIHYgaXMgbm90IE5vbmUgYW5kIHYudGV4dDoKICAgICAgICAgICAgICAgICAgICB2YWwgPSB2LnRleHQKICAgICAgICAgICAgY2VsbHNbY29sXSA9IHZhbC5zdHJpcCgpIGlmIHZhbCBlbHNlICIiCiAgICAgICAgcm93cy5hcHBlbmQoY2VsbHMpCiAgICByZXR1cm4gcm93cwoKCmRlZiBfZmluZF9wb19jb2x1bW4ocm93cywgcG9fbmFtZSk6CiAgICAiIiLlnKggcm93c1sxXe+8iOesrDLooYzmoIfpopjooYzvvInkuK3mn6Xmib7kuI4gcG9fbmFtZSDljLnphY3nmoTliJflrZfmr43vvIhCfkjvvInjgIIKICAgIOWMuemFjeinhOWIme+8muWFiOeyvuehruWMuemFjSDihpIg5Y675o6JIC5wbyDlkI7nvIDljLnphY0g4oaSIOmDveacquaJvuWIsOi/lOWbniBOb25lIiIiCiAgICBpZiBsZW4ocm93cykgPCAyOgogICAgICAgIHJldHVybiBOb25lCiAgICBoZWFkZXIgPSByb3dzWzFdCiAgICAjIOWOu+aOiSAucG8g5ZCO57yA55qE5Y+Y5L2TCiAgICBwb19zdGVtID0gcG9fbmFtZQogICAgaWYgcG9fc3RlbS5sb3dlcigpLmVuZHN3aXRoKCIucG8iKToKICAgICAgICBwb19zdGVtID0gcG9fc3RlbVs6LTNdCiAgICBjYW5kaWRhdGVzID0gW3BvX25hbWUsIHBvX3N0ZW1dCiAgICBmb3IgY29sIGluIFsnQicsICdDJywgJ0QnLCAnRScsICdGJywgJ0cnLCAnSCddOgogICAgICAgIGNlbGwgPSBoZWFkZXIuZ2V0KGNvbCwgJycpLnN0cmlwKCkKICAgICAgICBpZiBjZWxsIGluIGNhbmRpZGF0ZXM6CiAgICAgICAgICAgIHJldHVybiBjb2wKICAgIHJldHVybiBOb25lCgoKZGVmIGxvYWRfcnVsZXMoeGxzeF9wYXRoLCBwb19uYW1lKToKICAgICIiIuWKoOi9vee/u+ivkeinhOWIme+8jOaMiSBQTyDmlofku7blkI3ljLnphY3nrKwy6KGM5YiX5ZCN77yaCiAgICAtIOesrDHooYzvvJror7TmmI7vvIjot7Pov4fvvIkKICAgIC0g56ysMuihjO+8muWIl+agh+mimCDigJQgQT3ljp/mlodLZXksIEJ+SD3lkIRQT+aWh+S7tuWQjeagh+ivhgogICAgLSDnrKwz6KGM6LW377ya5qC55o2uIHBvX25hbWUg5Yy56YWN55qE5YiX6K+75Y+W5a+55bqU6K+R5paHCiAgICAtIOOAi+ato+WImeS/neaKpO+8muWFqOWxgOeUn+aViO+8iEHliJfmraPliJnvvInvvIzkuI3otbDliJfljLnphY0KICAgIC0g44CL5L2/55So6K+05piOIFNoZWV077ya6Lez6L+HCiAgICAiIiIKICAgIGRlZmF1bHQgPSB7CiAgICAgICAgInJlZ2V4X3Byb3RlY3QiOiBbXSwKICAgICAgICAiZXhhY3RfbWF0Y2giOiB7fSwKICAgICAgICAiY29udGV4dF9tYXRjaCI6IFtdLAogICAgICAgICJwcmVmaXhfcnVsZXMiOiBbXSwKICAgICAgICAic3VmZml4X3J1bGVzIjogW10sCiAgICAgICAgInN1YnN0cmluZyI6IFtdLAogICAgfQogICAgaWYgbm90IHhsc3hfcGF0aCBvciBub3Qgb3MucGF0aC5pc2ZpbGUoeGxzeF9wYXRoKToKICAgICAgICByZXR1cm4gZGVmYXVsdAoKICAgIHRyeToKICAgICAgICB6ZiA9IHppcGZpbGUuWmlwRmlsZSh4bHN4X3BhdGgsICdyJykKCiAgICAgICAgIyDor7vlj5blhbHkuqvlrZfnrKbkuLLooajvvIhFeGNlbCDlpKflpJrmlbDmlofmnKzlrZjlgqjlnKjmraTvvIkKICAgICAgICBzaGFyZWRfc3RyaW5ncyA9IF9yZWFkX3NoYXJlZF9zdHJpbmdzKHpmKQogICAgICAgIGxvZygiICBTaGFyZWRTdHJpbmdzIGNvdW50OiAlZCIgJSBsZW4oc2hhcmVkX3N0cmluZ3MpKQoKICAgICAgICB3Yl94bWwgPSB6Zi5yZWFkKCd4bC93b3JrYm9vay54bWwnKS5kZWNvZGUoJ3V0Zi04JykKICAgICAgICB3Yl9yb290ID0gRVQuZnJvbXN0cmluZyh3Yl94bWwpCiAgICAgICAgbnMgPSB7J3MnOiAnaHR0cDovL3NjaGVtYXMub3BlbnhtbGZvcm1hdHMub3JnL3NwcmVhZHNoZWV0bWwvMjAwNi9tYWluJ30KICAgICAgICBzaGVldHMgPSBbXQogICAgICAgIGZvciBzaGVldCBpbiB3Yl9yb290LmZpbmRhbGwoJy4vL3M6c2hlZXQnLCBucyk6CiAgICAgICAgICAgIG5hbWUgPSBzaGVldC5nZXQoIm5hbWUiLCAiIikKICAgICAgICAgICAgc2lkID0gc2hlZXQuZ2V0KCJzaGVldElkIiwgIiIpCiAgICAgICAgICAgIHNoZWV0X2ZpbGUgPSAieGwvd29ya3NoZWV0cy9zaGVldCVzLnhtbCIgJSBzaWQKICAgICAgICAgICAgc2hlZXRzLmFwcGVuZCgobmFtZSwgc2hlZXRfZmlsZSkpCgogICAgICAgIGZvciBzaGVldF9uYW1lLCBzaGVldF9maWxlIGluIHNoZWV0czoKICAgICAgICAgICAgaWYgc2hlZXRfbmFtZSA9PSAi44CL5L2/55So6K+05piOIjoKICAgICAgICAgICAgICAgIGNvbnRpbnVlCgogICAgICAgICAgICByb3dzID0gX3JlYWRfeGxzeF9zaGVldCh6Ziwgc2hlZXRfZmlsZSwgc2hhcmVkX3N0cmluZ3MpCiAgICAgICAgICAgIHBvX2NvbCA9IF9maW5kX3BvX2NvbHVtbihyb3dzLCBwb19uYW1lKSAgIyDljLnphY1QT+aWh+S7tuWvueW6lOeahOWIlwoKICAgICAgICAgICAgaWYgc2hlZXRfbmFtZS5zdGFydHN3aXRoKCLjgIsiKToKICAgICAgICAgICAgICAgICMgLS0tLSDkuJPnlKjop4TliJkgU2hlZXQgLS0tLQogICAgICAgICAgICAgICAgaWYgIuato+WImeS/neaKpCIgaW4gc2hlZXRfbmFtZToKICAgICAgICAgICAgICAgICAgICAjIOWFqOWxgOeUn+aViO+8jOWni+e7iOivuyBBIOWIlwogICAgICAgICAgICAgICAgICAgIGZvciByIGluIHJvd3NbMjpdOgogICAgICAgICAgICAgICAgICAgICAgICBwYXQgPSByLmdldCgnQScsICcnKQogICAgICAgICAgICAgICAgICAgICAgICBpZiBwYXQ6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGVmYXVsdFsicmVnZXhfcHJvdGVjdCJdLmFwcGVuZChyZS5jb21waWxlKHBhdCkpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgbG9nKCIgIHJlZ2V4X3Byb3RlY3Q6ICVzIiAlIHBhdCkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBsb2coIiAgcmVnZXhfcHJvdGVjdCBFUlJPUjogJXMgfCAlcyIgJSAocGF0LCBzdHIoZSkpKQoKICAgICAgICAgICAgICAgIGVsaWYgIuWJjeWQjue8gCIgaW4gc2hlZXRfbmFtZSBhbmQgcG9fY29sOgogICAgICAgICAgICAgICAgICAgIGZvciByIGluIHJvd3NbMjpdOgogICAgICAgICAgICAgICAgICAgICAgICB0ZXh0ID0gci5nZXQoJ0EnLCAnJykKICAgICAgICAgICAgICAgICAgICAgICAgcG9zID0gci5nZXQoJ0InLCAnJykuc3RyaXAoKQogICAgICAgICAgICAgICAgICAgICAgICB0cmFucyA9IHIuZ2V0KHBvX2NvbCwgJycpCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIHRleHQgYW5kIHRyYW5zOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgaWYgJ+WJjee8gCcgaW4gcG9zOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRlZmF1bHRbInByZWZpeF9ydWxlcyJdLmFwcGVuZCh7InRleHQiOiB0ZXh0LCAidHJhbnMiOiB0cmFuc30pCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgbG9nKCIgIHByZWZpeDogJyVzJyDihpIgJyVzJyIgJSAodGV4dCwgdHJhbnMpKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgZWxpZiAn5ZCO57yAJyBpbiBwb3M6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGVmYXVsdFsic3VmZml4X3J1bGVzIl0uYXBwZW5kKHsidGV4dCI6IHRleHQsICJ0cmFucyI6IHRyYW5zfSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBsb2coIiAgc3VmZml4OiAnJXMnIOKGkiAnJXMnIiAlICh0ZXh0LCB0cmFucykpCgogICAgICAgICAgICAgICAgZWxpZiAi54mH5q615Yy56YWNIiBpbiBzaGVldF9uYW1lIGFuZCBwb19jb2w6CiAgICAgICAgICAgICAgICAgICAgZm9yIHIgaW4gcm93c1syOl06CiAgICAgICAgICAgICAgICAgICAgICAgIHNyYyA9IHIuZ2V0KCdBJywgJycpCiAgICAgICAgICAgICAgICAgICAgICAgIGRzdCA9IHIuZ2V0KHBvX2NvbCwgJycpCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIHNyYyBhbmQgZHN0OgogICAgICAgICAgICAgICAgICAgICAgICAgICAgZGVmYXVsdFsic3Vic3RyaW5nIl0uYXBwZW5kKHsic3JjIjogc3JjLCAiZHN0IjogZHN0fSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGxvZygiICBzdWJzdHJpbmc6ICclcycg4oaSICclcyciICUgKHNyYywgZHN0KSkKCiAgICAgICAgICAgICAgICBlbGlmICLnsr7noa7ljLnphY0iIGluIHNoZWV0X25hbWUgYW5kIHBvX2NvbDoKICAgICAgICAgICAgICAgICAgICBmb3IgciBpbiByb3dzWzI6XToKICAgICAgICAgICAgICAgICAgICAgICAgc3JjID0gci5nZXQoJ0EnLCAnJykKICAgICAgICAgICAgICAgICAgICAgICAgZHN0ID0gci5nZXQocG9fY29sLCAnJykKICAgICAgICAgICAgICAgICAgICAgICAgaWYgc3JjIGFuZCBkc3Q6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBkZWZhdWx0WyJleGFjdF9tYXRjaCJdW3NyY10gPSBkc3QKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGxvZygiICBleGFjdF9tYXRjaDogJyVzJyDihpIgJyVzJyIgJSAoc3JjLCBkc3QpKQoKICAgICAgICAgICAgICAgIGVsaWYgIuivreWig+e/u+ivkSIgaW4gc2hlZXRfbmFtZSBhbmQgcG9fY29sOgogICAgICAgICAgICAgICAgICAgIGZvciByIGluIHJvd3NbMjpdOgogICAgICAgICAgICAgICAgICAgICAgICBtc2dpZCA9IHIuZ2V0KCdBJywgJycpCiAgICAgICAgICAgICAgICAgICAgICAgIGtleXdvcmQgPSByLmdldCgnQicsICcnKQogICAgICAgICAgICAgICAgICAgICAgICB0cmFucyA9IHIuZ2V0KHBvX2NvbCwgJycpCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIG1zZ2lkIGFuZCBrZXl3b3JkIGFuZCB0cmFuczoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRlZmF1bHRbImNvbnRleHRfbWF0Y2giXS5hcHBlbmQoewogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJtc2dpZCI6IG1zZ2lkLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJrZXl3b3JkIjoga2V5d29yZCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidHJhbnMiOiB0cmFucwogICAgICAgICAgICAgICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGxvZygiICBjb250ZXh0OiAnJXMnICM6JXMg4oaSICclcyciICUgKG1zZ2lkLCBrZXl3b3JkLCB0cmFucykpCiAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICAjIC0tLS0g5pmu6YCaIFNoZWV077yaQT1tc2dpZCwg5Yy56YWN5YiXPeivkeaWhyAtLS0tCiAgICAgICAgICAgICAgICBpZiBwb19jb2w6CiAgICAgICAgICAgICAgICAgICAgZm9yIHIgaW4gcm93c1syOl06CiAgICAgICAgICAgICAgICAgICAgICAgIHNyYyA9IHIuZ2V0KCdBJywgJycpCiAgICAgICAgICAgICAgICAgICAgICAgIGRzdCA9IHIuZ2V0KHBvX2NvbCwgJycpCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIHNyYyBhbmQgZHN0OgogICAgICAgICAgICAgICAgICAgICAgICAgICAgZGVmYXVsdFsiZXhhY3RfbWF0Y2giXVtzcmNdID0gZHN0CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBsb2coIiAgcGxhaW4gdGFibGUgJyVzJzogJyVzJyDihpIgJyVzJyIgJSAoc2hlZXRfbmFtZSwgc3JjLCBkc3QpKQoKICAgICAgICB6Zi5jbG9zZSgpCiAgICAgICAgcmV0dXJuIGRlZmF1bHQKCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgbG9nKCIgIGxvYWRfcnVsZXMgRVJST1I6ICVzIiAlIHN0cihlKSkKICAgICAgICB0cmFjZWJhY2sucHJpbnRfZXhjKGZpbGU9c3lzLnN0ZGVycikKICAgICAgICByZXR1cm4gZGVmYXVsdAoKCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMgIOinhOWImeW8leaTju+8muWwhuinhOWImeW6lOeUqOWIsOWNleS4quadoeebrgojICDov5Tlm54gKHRyYW5zbGF0ZWRfdGV4dCwgc291cmNlX3R5cGUpIOaIliAoTm9uZSwgTm9uZSkKIyAg5omn6KGM6aG65bqP77ya5q2j5YiZ5L+d5oqk77yI5pqC5a2Y77yJ4oaSIOeyvuehruWMuemFjSDihpIg6K+t5aKDIOKGkiDliY3lkI7nvIAg4oaSIOeJh+autQojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKZGVmIGFwcGx5X3J1bGVzKG1pZCwgY3R4LCBjdHh4LCBydWxlcyk6CiAgICAiIiIKICAgIG1pZDogbXNnaWQKICAgIGN0eDogbXNnY3R4dAogICAgY3R4eDogUE8g5Y6f5paH5LitICM6IOazqOmHiuihjOeahOWGheWuue+8iOeUqOS6juivreWig+WMuemFje+8iQogICAgcnVsZXM6IGxvYWRfcnVsZXMoKSDov5Tlm57nmoTnu5PmnoQKICAgIOi/lOWbniAodHJhbnNsYXRlZF90ZXh0LCAicnVsZSIpIOaIliAoTm9uZSwgTm9uZSkKICAgICIiIgogICAgaWYgbm90IHJ1bGVzOgogICAgICAgIHJldHVybiBOb25lLCBOb25lCgogICAgIyAxLiDnsr7noa7ljLnphY3vvJrmlbTmnaEgbXNnaWQg5a6M5YWo55u4562JCiAgICBpZiBtaWQgaW4gcnVsZXMuZ2V0KCJleGFjdF9tYXRjaCIsIHt9KToKICAgICAgICByZXR1cm4gcnVsZXNbImV4YWN0X21hdGNoIl1bbWlkXSwgInJ1bGUiCgogICAgIyAyLiDor63looPnv7vor5HvvJptc2dpZCArICM6IOWFs+mUruivjeWMuemFjQogICAgZm9yIGNtIGluIHJ1bGVzLmdldCgiY29udGV4dF9tYXRjaCIsIFtdKToKICAgICAgICBpZiBjbVsibXNnaWQiXSA9PSBtaWQgYW5kIGNtWyJrZXl3b3JkIl0gaW4gY3R4eDoKICAgICAgICAgICAgcmV0dXJuIGNtWyJ0cmFucyJdLCAicnVsZSIKCiAgICAjIDMuIOWJjeWQjue8gCArIOeJh+aute+8iOe7hOWQiOe/u+ivke+8iQogICAgcmVzdWx0ID0gbWlkCgogICAgIyAzYS4g5YmN57yA5pu/5o2iCiAgICBmb3IgcHIgaW4gcnVsZXMuZ2V0KCJwcmVmaXhfcnVsZXMiLCBbXSk6CiAgICAgICAgaWYgcmVzdWx0LnN0YXJ0c3dpdGgocHJbInRleHQiXSk6CiAgICAgICAgICAgIHJlc3VsdCA9IHByWyJ0cmFucyJdICsgcmVzdWx0W2xlbihwclsidGV4dCJdKTpdCiAgICAgICAgICAgIGJyZWFrICAjIOWPquWMuemFjeesrOS4gOS4qgoKICAgICMgM2IuIOWQjue8gOabv+aNogogICAgZm9yIHNyIGluIHJ1bGVzLmdldCgic3VmZml4X3J1bGVzIiwgW10pOgogICAgICAgIGlmIHJlc3VsdC5lbmRzd2l0aChzclsidGV4dCJdKToKICAgICAgICAgICAgcmVzdWx0ID0gcmVzdWx0WzotbGVuKHNyWyJ0ZXh0Il0pXSArIHNyWyJ0cmFucyJdCiAgICAgICAgICAgIGJyZWFrICAjIOWPquWMuemFjeesrOS4gOS4qgoKICAgICMgM2MuIOeJh+auteabv+aNogogICAgZm9yIHN1YiBpbiBydWxlcy5nZXQoInN1YnN0cmluZyIsIFtdKToKICAgICAgICByZXN1bHQgPSByZXN1bHQucmVwbGFjZShzdWJbInNyYyJdLCBzdWJbImRzdCJdKQoKICAgIGlmIHJlc3VsdCAhPSBtaWQ6CiAgICAgICAgcmV0dXJuIHJlc3VsdCwgInJ1bGUiCgogICAgcmV0dXJuIE5vbmUsIE5vbmUKCgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQojICBBSSDnv7vor5HliY3vvJrnlKjmraPliJnkv53miqTopoHkv53nlZnnmoTpg6jliIYKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KCmRlZiBwcm90ZWN0X2Zvcl9haShtaWQsIHJ1bGVzKToKICAgICIiIui/lOWbniAocHJvdGVjdGVkX3RleHQsIHBsYWNlaG9sZGVyc19kaWN0KQogICAgcHJvdGVjdGVkX3RleHQg5Lit77yM5q2j5YiZ5Yy56YWN55qE6YOo5YiG6KKr5pu/5o2i5Li6IF9fUE9fUFJPVEVDVF9OX18g5Y2g5L2N56ymCiAgICDnv7vor5HlkI7lho3nlKggcmVzdG9yZV9mcm9tX3Byb3RlY3Rpb24g6L+Y5Y6fCiAgICAiIiIKICAgIGlmIG5vdCBydWxlcyBvciBub3QgcnVsZXMuZ2V0KCJyZWdleF9wcm90ZWN0Iik6CiAgICAgICAgcmV0dXJuIG1pZCwge30KCiAgICBwbGFjZWhvbGRlcnMgPSB7fQogICAgY291bnRlciA9IFswXSAgIyDnlKjliJfooajljIXoo4XvvIzpgb/lhY3pl63ljIUgbm9ubG9jYWwg6Zeu6aKYCiAgICBmb3IgcGF0IGluIHJ1bGVzWyJyZWdleF9wcm90ZWN0Il06CiAgICAgICAgZGVmIF9yZXBsYWNlcihtLCBfcGF0PXBhdCk6CiAgICAgICAgICAgIGtleSA9ICJfX1BPX1BST1RFQ1RfJWRfXyIgJSBjb3VudGVyWzBdCiAgICAgICAgICAgIHBsYWNlaG9sZGVyc1trZXldID0gbS5ncm91cCgwKQogICAgICAgICAgICBjb3VudGVyWzBdICs9IDEKICAgICAgICAgICAgcmV0dXJuIGtleQogICAgICAgIG1pZCA9IHBhdC5zdWIoX3JlcGxhY2VyLCBtaWQpCgogICAgcmV0dXJuIG1pZCwgcGxhY2Vob2xkZXJzCgpkZWYgcmVzdG9yZV9mcm9tX3Byb3RlY3Rpb24odGV4dCwgcGxhY2Vob2xkZXJzKToKICAgICIiIuWwhuWNoOS9jeespui/mOWOn+S4uuWOn+Wni+aWh+acrCIiIgogICAgaWYgbm90IHBsYWNlaG9sZGVyczoKICAgICAgICByZXR1cm4gdGV4dAogICAgZm9yIGtleSwgdmFsIGluIHBsYWNlaG9sZGVycy5pdGVtcygpOgogICAgICAgIHRleHQgPSB0ZXh0LnJlcGxhY2Uoa2V5LCB2YWwpCiAgICByZXR1cm4gdGV4dAoKCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMgIOe/u+ivkeiusOW/huivu+WPlgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKZGVmIHJlYWRfbWVtb3J5KG1lbW9yeV9wYXRoKToKICAgIGlmIG5vdCBvcy5wYXRoLmlzZmlsZShtZW1vcnlfcGF0aCk6CiAgICAgICAgbG9nKCIgIE1lbW9yeSBmaWxlIG5vdCBmb3VuZDogJXMiICUgbWVtb3J5X3BhdGgpCiAgICAgICAgcmV0dXJuIHt9CiAgICB0cnk6CiAgICAgICAgd2l0aCBvcGVuKG1lbW9yeV9wYXRoLCAiciIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgICAgIGRhdGEgPSBqc29uLmxvYWQoZikKICAgICAgICAjIOWPquWPliBjb3VudD49MiDnmoTmnaHnm64KICAgICAgICByZXN1bHQgPSB7fQogICAgICAgIGZvciBrLCB2IGluIGRhdGEuaXRlbXMoKToKICAgICAgICAgICAgaWYgaXNpbnN0YW5jZSh2LCBkaWN0KSBhbmQgdi5nZXQoImNvdW50IiwgMCkgPj0gMjoKICAgICAgICAgICAgICAgIHRleHQgPSB2LmdldCgidGV4dCIsICIiKQogICAgICAgICAgICAgICAgaWYgdGV4dDoKICAgICAgICAgICAgICAgICAgICByZXN1bHRba10gPSB0ZXh0CiAgICAgICAgbG9nKCIgIExvYWRlZCAlZCBtZW1vcmllcyAoY291bnQ+PTIpIGZyb20gJXMiICUgKGxlbihyZXN1bHQpLCBtZW1vcnlfcGF0aCkpCiAgICAgICAgcmV0dXJuIHJlc3VsdAogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIGxvZygiICBNZW1vcnkgcmVhZCBFUlJPUjogJXMiICUgc3RyKGUpKQogICAgICAgIHJldHVybiB7fQoKCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMgIEFJIOe/u+ivkQojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKZGVmIHRyYW5zbGF0ZV9vbmUodGV4dCk6CiAgICB0cnk6CiAgICAgICAgcSA9IHVybGxpYi5wYXJzZS5xdW90ZSh0ZXh0LmVuY29kZSgidXRmLTgiKSkKICAgICAgICB1cmwgPSBFTkRQT0lOVCArICI/Y2xpZW50PWd0eCZkdD10JnNsPSVzJnRsPSVzJnE9JXMiICUgKAogICAgICAgICAgICB1cmxsaWIucGFyc2UucXVvdGUoc3JjX2xhbmcpLCB1cmxsaWIucGFyc2UucXVvdGUodGFyZ2V0X2xhbmcpLCBxCiAgICAgICAgKQogICAgICAgIHJlcSA9IHVybGxpYi5yZXF1ZXN0LlJlcXVlc3QodXJsLCBoZWFkZXJzPUhEUiwgbWV0aG9kPSJHRVQiKQogICAgICAgIHIgPSB1cmxsaWIucmVxdWVzdC51cmxvcGVuKHJlcSwgdGltZW91dD1USU1FT1VUKQogICAgICAgIGJvZHkgPSByLnJlYWQoKS5kZWNvZGUoZXJyb3JzPSJyZXBsYWNlIikKICAgICAgICBkYXRhID0ganNvbi5sb2Fkcyhib2R5KQogICAgICAgIGlmIGlzaW5zdGFuY2UoZGF0YSwgbGlzdCkgYW5kIGxlbihkYXRhKSA+IDAgYW5kIGlzaW5zdGFuY2UoZGF0YVswXSwgbGlzdCk6CiAgICAgICAgICAgIHBhcnRzID0gW10KICAgICAgICAgICAgZm9yIHNlZyBpbiBkYXRhWzBdOgogICAgICAgICAgICAgICAgaWYgaXNpbnN0YW5jZShzZWcsIGxpc3QpIGFuZCBsZW4oc2VnKSA+IDA6CiAgICAgICAgICAgICAgICAgICAgcGFydHMuYXBwZW5kKHN0cihzZWdbMF0pKQogICAgICAgICAgICByZXN1bHQgPSAiIi5qb2luKHBhcnRzKQogICAgICAgICAgICBpZiByZXN1bHQ6CiAgICAgICAgICAgICAgICByZXR1cm4gcmVzdWx0CiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgbG9nKCIgIHRyYW5zbGF0ZV9vbmUgRVJST1I6ICVzIHwgdGV4dD0lcyIgJSAoc3RyKGUpLCB0ZXh0Wzo2MF0pKQogICAgcmV0dXJuICIiCgpkZWYgd3JpdGVfcHJvZ3Jlc3MoZG9uZSwgdG90YWwsIGN1cnJlbnQpOgogICAgd2l0aCBvcGVuKHByb2dyZXNzX3BhdGgsICJ3IiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBqc29uLmR1bXAoeyJkb25lIjogZG9uZSwgInRvdGFsIjogdG90YWwsICJjdXJyZW50IjogY3VycmVudH0sIGYpCgoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KIyAg5Li75rWB56iL77ya6KeE5YiZIOKGkiDorrDlv4Yg4oaSIEFJCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Cgp0cnk6CiAgICBsb2coIlBhcnNpbmcgUE8gZmlsZS4uLiIpCiAgICBlbnRyaWVzLCBoZWFkZXIsIGNvbnRleHRzID0gcGFyc2VfcG8ocG9fcGF0aCkKICAgIHRvdGFsID0gbGVuKGVudHJpZXMpCiAgICBsb2coIlBhcnNlZCAlZCBlbnRyaWVzLCBoZWFkZXIgbGVuPSVkIiAlICh0b3RhbCwgbGVuKGhlYWRlcikpKQoKICAgICMg5om+5Ye65omA5pyJ56m6IG1zZ3N0ciDnmoTmnaHnm64KICAgIHBlbmRpbmcgPSBbXQogICAgZm9yIGksIChjdHgsIG1pZCwgbXN0cikgaW4gZW51bWVyYXRlKGVudHJpZXMpOgogICAgICAgIGlmIG1zdHIgPT0gIiIgYW5kIG1pZCAhPSAiIjoKICAgICAgICAgICAgcGVuZGluZy5hcHBlbmQoaSkKCiAgICBsb2coIlBlbmRpbmcgKGVtcHR5IG1zZ3N0cik6ICVkIiAlIGxlbihwZW5kaW5nKSkKCiAgICBpZiBub3QgcGVuZGluZzoKICAgICAgICB3cml0ZV9wcm9ncmVzcygwLCAwLCAiIikKICAgICAgICB3aXRoIG9wZW4ocmVzdWx0X3BhdGgsICJ3IiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICAgICAganNvbi5kdW1wKHsib2siOiBUcnVlLCAidHJhbnNsYXRlZCI6IDAsICJ0b3RhbCI6IHRvdGFsLCAic291cmNlcyI6IHt9fSwgZikKICAgICAgICBwcmludChqc29uLmR1bXBzKHsib2siOiBUcnVlLCAidHJhbnNsYXRlZCI6IDAsICJ0b3RhbCI6IHRvdGFsfSkpCiAgICAgICAgc3lzLmV4aXQoMCkKCiAgICAjIC0tLS0g5Yqg6L296KeE5YiZ5ZKM6K6w5b+GIC0tLS0KICAgIHJ1bGVzID0gTm9uZQogICAgbWVtb3J5ID0ge30KICAgIGlmIHByb2plY3RfcGF0aDoKICAgICAgICBwb19iYXNlbmFtZSA9IG9zLnBhdGguc3BsaXRleHQob3MucGF0aC5iYXNlbmFtZShwb19wYXRoKSlbMF0KICAgICAgICBydWxlc194bHN4ID0gb3MucGF0aC5qb2luKHByb2plY3RfcGF0aCwgIue/u+ivkeinhOWImS54bHN4IikKICAgICAgICBtZW1vcnlfanNvbiA9IG9zLnBhdGguam9pbihwcm9qZWN0X3BhdGgsICLnv7vor5HorrDlv4YiLCAidHJhbnNsYXRlX21lbW9yeS5qc29uIikKICAgICAgICBsb2coIkxvYWRpbmcgcnVsZXMgZnJvbTogJXMgKHBvPSVzKSIgJSAocnVsZXNfeGxzeCwgcG9fYmFzZW5hbWUpKQogICAgICAgIHJ1bGVzID0gbG9hZF9ydWxlcyhydWxlc194bHN4LCBwb19iYXNlbmFtZSkKICAgICAgICBsb2coIkxvYWRpbmcgbWVtb3J5IGZyb206ICVzIiAlIG1lbW9yeV9qc29uKQogICAgICAgIG1lbW9yeSA9IHJlYWRfbWVtb3J5KG1lbW9yeV9qc29uKQogICAgZWxzZToKICAgICAgICBsb2coIk5vIHByb2plY3RfcGF0aCwgc2tpcHBpbmcgcnVsZXMgYW5kIG1lbW9yeSIpCgogICAgIyAtLS0tIOS4u+e/u+ivkeW+queOr++8muinhOWImSDihpIg6K6w5b+GIOKGkiBBSe+8iOato+WImeS/neaKpOWMheijhSBBSe+8iSAtLS0tCiAgICBwZW5kaW5nX3RvdGFsID0gbGVuKHBlbmRpbmcpCiAgICB3cml0ZV9wcm9ncmVzcygwLCBwZW5kaW5nX3RvdGFsLCAic3RhcnQiKQoKICAgIHNvdXJjZXMgPSB7fSAgICAgICAjIHtlbnRyeV9pbmRleDogInJ1bGUifCJtZW1vcnkifCJhaSJ9CiAgICBzdWNjZXNzX2NvdW50ID0gMAogICAgZG9uZSA9IDAKICAgIGkgPSAwCgogICAgd2hpbGUgaSA8IHBlbmRpbmdfdG90YWw6CiAgICAgICAgYmF0Y2hfZW5kID0gbWluKGkgKyBiYXRjaF9zaXplLCBwZW5kaW5nX3RvdGFsKQogICAgICAgIGZvciBqIGluIHJhbmdlKGksIGJhdGNoX2VuZCk6CiAgICAgICAgICAgIGlkeCA9IHBlbmRpbmdbal0KICAgICAgICAgICAgY3R4LCBtaWQsIG1zdHIgPSBlbnRyaWVzW2lkeF0KICAgICAgICAgICAgY3R4eCA9IGNvbnRleHRzW2lkeF0gaWYgaWR4IDwgbGVuKGNvbnRleHRzKSBlbHNlICIiCiAgICAgICAgICAgIHJlc3VsdCA9ICIiCgogICAgICAgICAgICAjIDEpIOinhOWImeW8leaTjgogICAgICAgICAgICBpZiBydWxlczoKICAgICAgICAgICAgICAgIHJ1bGVfcmVzdWx0LCBfcnVsZV9zcmMgPSBhcHBseV9ydWxlcyhtaWQsIGN0eCwgY3R4eCwgcnVsZXMpCiAgICAgICAgICAgICAgICBpZiBydWxlX3Jlc3VsdDoKICAgICAgICAgICAgICAgICAgICByZXN1bHQgPSBydWxlX3Jlc3VsdAogICAgICAgICAgICAgICAgICAgIHNvdXJjZXNbc3RyKGlkeCldID0gInJ1bGUiCiAgICAgICAgICAgICAgICAgICAgbG9nKCIgIFslZF0gUlVMRTogJyVzJyDihpIgJyVzJyIgJSAoaWR4LCBtaWQsIHJlc3VsdCkpCgogICAgICAgICAgICAjIDIpIOe/u+ivkeiusOW/hu+8iOinhOWImeacquWRveS4reaXtu+8iQogICAgICAgICAgICBpZiBub3QgcmVzdWx0IGFuZCBtaWQgaW4gbWVtb3J5OgogICAgICAgICAgICAgICAgcmVzdWx0ID0gbWVtb3J5W21pZF0KICAgICAgICAgICAgICAgIHNvdXJjZXNbc3RyKGlkeCldID0gIm1lbW9yeSIKICAgICAgICAgICAgICAgIGxvZygiICBbJWRdIE1FTU9SWTogJyVzJyDihpIgJyVzJyIgJSAoaWR4LCBtaWQsIHJlc3VsdCkpCgogICAgICAgICAgICAjIDMpIEFJIOe/u+ivke+8iOinhOWImeWSjOiusOW/humDveacquWRveS4re+8iQogICAgICAgICAgICBpZiBub3QgcmVzdWx0OgogICAgICAgICAgICAgICAgIyDmraPliJnkv53miqTvvJrmiorljaDkvY3nrKYv5qCH562+5pu/5o2i5Li65Y2g5L2N5qCH6K6w77yM57+76K+R5ZCO6L+Y5Y6fCiAgICAgICAgICAgICAgICBwcm90ZWN0ZWRfbWlkLCBwbGFjZWhvbGRlcnMgPSBwcm90ZWN0X2Zvcl9haShtaWQsIHJ1bGVzKSBpZiBydWxlcyBlbHNlIChtaWQsIHt9KQogICAgICAgICAgICAgICAgYWlfcmVzdWx0ID0gdHJhbnNsYXRlX29uZShwcm90ZWN0ZWRfbWlkKQogICAgICAgICAgICAgICAgaWYgYWlfcmVzdWx0OgogICAgICAgICAgICAgICAgICAgIHJlc3VsdCA9IHJlc3RvcmVfZnJvbV9wcm90ZWN0aW9uKGFpX3Jlc3VsdCwgcGxhY2Vob2xkZXJzKQogICAgICAgICAgICAgICAgICAgIHNvdXJjZXNbc3RyKGlkeCldID0gImFpIgogICAgICAgICAgICAgICAgICAgIGxvZygiICBbJWRdIEFJOiAnJXMnIOKGkiAnJXMnIiAlIChpZHgsIG1pZCwgcmVzdWx0KSkKCiAgICAgICAgICAgIGlmIHJlc3VsdDoKICAgICAgICAgICAgICAgIGVudHJpZXNbaWR4XSA9IChjdHgsIG1pZCwgcmVzdWx0KQogICAgICAgICAgICAgICAgc3VjY2Vzc19jb3VudCArPSAxCgogICAgICAgICAgICBkb25lICs9IDEKICAgICAgICAgICAgaWYgZG9uZSAlIDUgPT0gMCBvciBkb25lID09IHBlbmRpbmdfdG90YWw6CiAgICAgICAgICAgICAgICB3cml0ZV9wcm9ncmVzcyhkb25lLCBwZW5kaW5nX3RvdGFsLCBtaWRbOjQwXSkKCiAgICAgICAgaSA9IGJhdGNoX2VuZAogICAgICAgIGxvZygiQmF0Y2ggZG9uZTogJWQvJWQsIHN1Y2Nlc3M6ICVkIiAlIChpLCBwZW5kaW5nX3RvdGFsLCBzdWNjZXNzX2NvdW50KSkKICAgICAgICByZXBsYWNlX21zZ3N0cl9pbnBsYWNlKHBvX3BhdGgsIGVudHJpZXMsIGhlYWRlcikKCiAgICB3cml0ZV9wcm9ncmVzcyhwZW5kaW5nX3RvdGFsLCBwZW5kaW5nX3RvdGFsLCAiZG9uZSIpCgogICAgbG9nKCJBbGwgZG9uZS4gVHJhbnNsYXRlZCAlZC8lZC4gU291cmNlczogcnVsZT0lZCBtZW1vcnk9JWQgYWk9JWQiICUgKAogICAgICAgIHN1Y2Nlc3NfY291bnQsCiAgICAgICAgc3VtKDEgZm9yIHYgaW4gc291cmNlcy52YWx1ZXMoKSBpZiB2ID09ICJydWxlIiksCiAgICAgICAgc3VtKDEgZm9yIHYgaW4gc291cmNlcy52YWx1ZXMoKSBpZiB2ID09ICJtZW1vcnkiKSwKICAgICAgICBzdW0oMSBmb3IgdiBpbiBzb3VyY2VzLnZhbHVlcygpIGlmIHYgPT0gImFpIikKICAgICkpCgogICAgZmluYWxfcmVzdWx0ID0geyJvayI6IFRydWUsICJ0cmFuc2xhdGVkIjogc3VjY2Vzc19jb3VudCwgInRvdGFsIjogdG90YWwsICJzb3VyY2VzIjogc291cmNlc30KICAgIHdpdGggb3BlbihyZXN1bHRfcGF0aCwgInciLCBlbmNvZGluZz0idXRmLTgiKSBhcyBmOgogICAgICAgIGpzb24uZHVtcChmaW5hbF9yZXN1bHQsIGYpCgogICAgcHJpbnQoanNvbi5kdW1wcyhmaW5hbF9yZXN1bHQpKQoKZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgbG9nKCJGQVRBTCBFUlJPUjogJXMiICUgc3RyKGUpKQogICAgdHJhY2ViYWNrLnByaW50X2V4YyhmaWxlPXN5cy5zdGRlcnIpCiAgICB3aXRoIG9wZW4ocmVzdWx0X3BhdGgsICJ3IiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBqc29uLmR1bXAoeyJvayI6IEZhbHNlLCAidHJhbnNsYXRlZCI6IDAsICJ0b3RhbCI6IDAsICJtZXNzYWdlIjogc3RyKGUpfSwgZikKICAgIHByaW50KGpzb24uZHVtcHMoeyJvayI6IEZhbHNlLCAidHJhbnNsYXRlZCI6IDAsICJ0b3RhbCI6IDAsICJtZXNzYWdlIjogc3RyKGUpfSkpCg=="

## 共享结果（仅 API 检测使用）
static var _api_check_result: Dictionary = {}

## 将 Python 脚本拷贝到 user:// 临时路径
static func copy_script_to_temp(script_name: String = "_po_full_translate.py") -> String:
	var content := _read_py_script()
	if content.is_empty():
		return ""
	var dst_path := OS.get_user_data_dir().path_join(script_name)
	var dst := FileAccess.open(dst_path, FileAccess.WRITE)
	if dst == null:
		return ""
	dst.store_string(content)
	dst.close()
	return dst_path

## 读取脚本内容：优先 res:// 文件 → exe 同级 → 内嵌 Base64
static func _read_py_script() -> String:
	# 策略 1：res:// 文件
	var src := FileAccess.open(PY_SCRIPT_PATH, FileAccess.READ)
	if src:
		var c := src.get_as_text(); src.close()
		return c

	# 策略 2：exe 同级目录
	if not OS.has_feature("editor"):
		var exe_dir := OS.get_executable_path().get_base_dir()
		var exe_py := exe_dir.path_join("translate_full.py.txt")
		src = FileAccess.open(exe_py, FileAccess.READ)
		if src:
			var c := src.get_as_text(); src.close()
			return c

	# 策略 3：内嵌 Base64（保证可用）
	if not EMBEDDED_PY_B64.is_empty():
		return Marshalls.base64_to_utf8(EMBEDDED_PY_B64)

	return ""


# ======== API 检测 ========

static func check_api(url: String, api_type: String = "google"):
	_api_check_result = _do_check(url, api_type)

static func _do_check(url: String, api_type: String) -> Dictionary:
	var cmd := _find_python()
	if cmd.is_empty():
		return {"available": false, "message": "Python 不可用"}

	var check_script := ""
	if api_type == "libretranslate":
		check_script = """
import json, sys, urllib.request, ssl
url = sys.argv[1].rstrip("/") + "/translate"
ctx = ssl.create_default_context()
hdr = {"User-Agent": "Mozilla/5.0", "Content-Type": "application/json"}
payload = json.dumps({"q": "test", "source": "en", "target": "zh-Hans", "format": "text"}).encode("utf-8")
try:
    req = urllib.request.Request(url, data=payload, headers=hdr, method="POST")
    r = urllib.request.urlopen(req, timeout=10, context=ctx)
    body = r.read().decode(errors="replace")
    data = json.loads(body)
    ok = isinstance(data, dict) and "translatedText" in data
    print(json.dumps({"available": ok, "message": "API OK" if ok else "bad response"}))
except Exception as e:
    print(json.dumps({"available": false, "message": str(e)}))
"""
	elif api_type == "baidu":
		check_script = """
import json, sys, urllib.request, ssl
ctx = ssl.create_default_context()
url = "https://fanyi.baidu.com/transapi"
payload = urllib.parse.urlencode({"query": "test", "from": "en", "to": "zh"}).encode("utf-8")
hdr = {"User-Agent": "Mozilla/5.0", "Referer": "https://fanyi.baidu.com/"}
try:
    req = urllib.request.Request(url, data=payload, headers=hdr, method="POST")
    r = urllib.request.urlopen(req, timeout=8, context=ctx)
    body = r.read().decode(errors="replace")
    data = json.loads(body)
    ok = isinstance(data, dict) and "data" in data and len(data.get("data", [])) > 0
    print(json.dumps({"available": ok, "message": "API OK" if ok else "bad response"}))
except Exception as e:
    print(json.dumps({"available": false, "message": str(e)}))
"""
	elif api_type == "youdao":
		check_script = """
import json, sys, urllib.request, ssl, hashlib, time
ctx = ssl.create_default_context()
t = str(int(time.time() * 1000))
salt = t
sign = hashlib.md5(("fanyideskweb" + t + salt + "Ygy_4c=r#e#4AX^@u").encode("utf-8")).hexdigest()
form_data = urllib.parse.urlencode({
    "i": "test",
    "from": "en",
    "to": "zh-CHS",
    "smartresult": "dict",
    "client": "fanyideskweb",
    "salt": salt,
    "sign": sign,
    "lts": t,
    "bv": hashlib.md5("5.0 (Windows)".encode("utf-8")).hexdigest(),
    "doctype": "json",
    "version": "2.1",
    "keyfrom": "fanyi.web",
    "action": "FY_BY_REALTlME",
}).encode("utf-8")
hdr = {"User-Agent": "Mozilla/5.0", "Referer": "https://fanyi.youdao.com/", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"}
try:
    req = urllib.request.Request("https://fanyi.youdao.com/translate?smartresult=dict&smartresult=rule", data=form_data, headers=hdr, method="POST")
    r = urllib.request.urlopen(req, timeout=8, context=ctx)
    body = r.read().decode(errors="replace")
    data = json.loads(body)
    ok = isinstance(data, dict) and "translateResult" in data and len(data.get("translateResult", [])) > 0
    print(json.dumps({"available": ok, "message": "API OK" if ok else "bad response"}))
except Exception as e:
    print(json.dumps({"available": false, "message": str(e)}))
"""
	else:
		check_script = """
import json, sys, urllib.request, ssl
url = sys.argv[1]
ctx = ssl.create_default_context()
hdr = {"User-Agent": "Mozilla/5.0"}
try:
    r = urllib.request.urlopen(urllib.request.Request(url, headers=hdr), timeout=8, context=ctx)
    body = r.read().decode(errors="replace")
    data = json.loads(body)
    ok = isinstance(data, list) and len(data) > 0
    print(json.dumps({"available": ok, "message": "API OK" if ok else "bad response"}))
except Exception as e:
    print(json.dumps({"available": false, "message": str(e)}))
"""
	var tmp_py := OS.get_user_data_dir().path_join("_po_check.py")
	var f := FileAccess.open(tmp_py, FileAccess.WRITE)
	if f == null:
		return {"available": false, "message": "无法写入脚本"}
	f.store_string(check_script)
	f.close()

	var out: Array = []
	var ec := OS.execute(cmd, [tmp_py, url], out, true)
	DirAccess.remove_absolute(tmp_py)
	if ec != 0 or out.is_empty():
		return {"available": false, "message": "请求失败"}
	var p = JSON.parse_string(out[0])
	if p is Dictionary:
		return {"available": p.get("available", false), "message": str(p.get("message", ""))}
	return {"available": false, "message": "解析失败"}


# ======== 单条翻译 ========

## 后台线程入口：结果写入调用方传入的 result_holder，避免并发任务互相覆盖
static func translate_single(text: String, src_lang: String, target_lang: String, api_type: String, api_url: String, result_holder: Dictionary):
	var r := _do_translate_single(text, src_lang, target_lang, api_type, api_url)
	result_holder["ok"] = r.get("ok", false)
	result_holder["text"] = r.get("text", "")
	result_holder["message"] = r.get("message", "")

static func _do_translate_single(text: String, src_lang: String, target_lang: String, api_type: String, api_url: String) -> Dictionary:
	var cmd := _find_python()
	if cmd.is_empty():
		return {"ok": false, "text": "", "message": "Python 不可用"}

	var script := """
import json, sys, base64, urllib.request, urllib.parse, ssl, re, hashlib, time
text = base64.b64decode(sys.argv[1]).decode("utf-8")
src_lang = sys.argv[2]
target_lang = sys.argv[3]
api_type = sys.argv[4]
api_url = sys.argv[5] if len(sys.argv) > 5 else ""
ctx = ssl.create_default_context()
def conv(code):
    m = {"zh-CN": "zh-Hans", "zh-TW": "zh-Hant", "auto": "auto"}
    return m.get(code, code)
def conv_baidu(code):
    m = {"zh-CN": "zh", "zh-TW": "cht", "auto": "auto", "ja": "jp", "ko": "kor", "fr": "fra", "de": "de", "es": "spa", "pt": "pt", "ru": "ru", "ar": "ara", "th": "th", "vi": "vie", "id": "id", "it": "it", "nl": "nl", "pl": "pl", "tr": "tr", "uk": "ukr", "he": "heb"}
    return m.get(code, code)
def conv_youdao(code):
    m = {"zh-CN": "zh-CHS", "zh-TW": "zh-CHT", "auto": "auto", "ja": "ja", "ko": "ko", "fr": "fr", "de": "de", "es": "es", "pt": "pt", "ru": "ru", "ar": "ar", "th": "th", "vi": "vi", "id": "id", "it": "it", "nl": "nl", "pl": "pl", "tr": "tr", "uk": "uk", "he": "he"}
    return m.get(code, code)
try:
    if api_type == "libretranslate":
        base = api_url.rstrip("/") if api_url else "http://localhost:5000"
        url = base + "/translate"
        payload = json.dumps({"q": text, "source": conv(src_lang), "target": conv(target_lang), "format": "text"}).encode("utf-8")
        hdr = {"User-Agent": "Mozilla/5.0", "Content-Type": "application/json"}
        req = urllib.request.Request(url, data=payload, headers=hdr, method="POST")
        r = urllib.request.urlopen(req, timeout=8, context=ctx)
        data = json.loads(r.read().decode(errors="replace"))
        if isinstance(data, dict) and "translatedText" in data:
            print(json.dumps({"ok": True, "text": data["translatedText"]}))
        else:
            print(json.dumps({"ok": False, "text": "", "message": "bad response"}))
    elif api_type == "baidu":
        payload = urllib.parse.urlencode({
            "query": text,
            "from": conv_baidu(src_lang),
            "to": conv_baidu(target_lang),
        }).encode("utf-8")
        hdr = {"User-Agent": "Mozilla/5.0", "Referer": "https://fanyi.baidu.com/"}
        r = urllib.request.urlopen(urllib.request.Request("https://fanyi.baidu.com/transapi", data=payload, headers=hdr), timeout=8, context=ctx)
        data = json.loads(r.read().decode(errors="replace"))
        result = ""
        if isinstance(data, dict) and "data" in data:
            for item in data["data"]:
                if isinstance(item, dict) and "dst" in item:
                    result += item["dst"]
        if result:
            print(json.dumps({"ok": True, "text": result}))
        else:
            print(json.dumps({"ok": False, "text": "", "message": "bad response"}))
    elif api_type == "youdao":
        t = str(int(time.time() * 1000))
        salt = t
        sign = hashlib.md5(("fanyideskweb" + t + salt + "Ygy_4c=r#e#4AX^@u").encode("utf-8")).hexdigest()
        form_data = urllib.parse.urlencode({
            "i": text,
            "from": conv_youdao(src_lang),
            "to": conv_youdao(target_lang),
            "smartresult": "dict",
            "client": "fanyideskweb",
            "salt": salt,
            "sign": sign,
            "lts": t,
            "bv": hashlib.md5("5.0 (Windows)".encode("utf-8")).hexdigest(),
            "doctype": "json",
            "version": "2.1",
            "keyfrom": "fanyi.web",
            "action": "FY_BY_REALTlME",
        }).encode("utf-8")
        hdr = {"User-Agent": "Mozilla/5.0", "Referer": "https://fanyi.youdao.com/", "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"}
        r = urllib.request.urlopen(urllib.request.Request("https://fanyi.youdao.com/translate?smartresult=dict&smartresult=rule", data=form_data, headers=hdr), timeout=8, context=ctx)
        data = json.loads(r.read().decode(errors="replace"))
        result = ""
        if isinstance(data, dict) and "translateResult" in data and len(data["translateResult"]) > 0:
            for seg in data["translateResult"][0]:
                if isinstance(seg, dict) and "tgt" in seg:
                    result += seg["tgt"]
        if result:
            print(json.dumps({"ok": True, "text": result}))
        else:
            print(json.dumps({"ok": False, "text": "", "message": "bad response"}))
    else:
        url = "https://translate.googleapis.com/translate_a/single?client=gtx&dt=t&sl=%s&tl=%s&q=%s" % (
            urllib.parse.quote(src_lang), urllib.parse.quote(target_lang), urllib.parse.quote(text.encode("utf-8"))
        )
        hdr = {"User-Agent": "Mozilla/5.0"}
        r = urllib.request.urlopen(urllib.request.Request(url, headers=hdr), timeout=8, context=ctx)
        body = r.read().decode(errors="replace")
        data = json.loads(body)
        if isinstance(data, list) and len(data) > 0 and isinstance(data[0], list):
            parts = []
            for seg in data[0]:
                if isinstance(seg, list) and len(seg) > 0:
                    parts.append(str(seg[0]))
            print(json.dumps({"ok": True, "text": "".join(parts)}))
        else:
            print(json.dumps({"ok": False, "text": "", "message": "bad response"}))
except Exception as e:
    print(json.dumps({"ok": False, "text": "", "message": str(e)}))
"""

	var tmp_py := OS.get_user_data_dir().path_join("_po_translate_single.py")
	var f := FileAccess.open(tmp_py, FileAccess.WRITE)
	if f == null:
		return {"ok": false, "text": "", "message": "无法写入脚本"}
	f.store_string(script)
	f.close()

	var out: Array = []
	var b64 := Marshalls.utf8_to_base64(text)
	var ec := OS.execute(cmd, [tmp_py, b64, src_lang, target_lang, api_type, api_url], out, true)
	DirAccess.remove_absolute(tmp_py)
	if ec != 0 or out.is_empty():
		return {"ok": false, "text": "", "message": "请求失败"}
	var p = JSON.parse_string(out[0])
	if p is Dictionary:
		return {"ok": bool(p.get("ok", false)), "text": str(p.get("text", "")), "message": str(p.get("message", ""))}
	return {"ok": false, "text": "", "message": "解析失败"}


# ======== 全流程翻译（纯执行器） ========

static func cancel_translate():
	_cancel_flag = true
	if _running_pid > 0:
		if OS.is_process_running(_running_pid):
			OS.kill(_running_pid)
		_running_pid = -1


static func run_full_translate(po_path: String, src_lang: String, target_lang: String, batch_size: int, progress_path: String, script_temp_path: String, project_path: String = "", api_type: String = "google", api_url: String = ""):
	_cancel_flag = false
	_write_bridge_log(progress_path, "bridge start")
	_write_bridge_log(progress_path, "  po_path=%s" % po_path)
	_write_bridge_log(progress_path, "  progress_path=%s" % progress_path)
	_write_bridge_log(progress_path, "  project_path=%s" % project_path)
	_write_bridge_log(progress_path, "  script_temp=%s" % script_temp_path)
	_write_bridge_log(progress_path, "  src=%s target=%s" % [src_lang, target_lang])
	_write_bridge_log(progress_path, "  api_type=%s api_url=%s" % [api_type, api_url])

	if FileAccess.file_exists(progress_path):
		DirAccess.remove_absolute(progress_path)

	var cmd := _find_python()
	_write_bridge_log(progress_path, "  python=%s" % cmd)

	if cmd.is_empty():
		_write_bridge_log(progress_path, "  ERROR: Python not found")
		return

	if script_temp_path.is_empty():
		_write_bridge_log(progress_path, "  ERROR: script path empty")
		return

	var args := PackedStringArray([script_temp_path, po_path, src_lang, target_lang, str(batch_size), progress_path, project_path, api_type, api_url])
	_write_bridge_log(progress_path, "  executing (create_process)...")

	var pid := OS.create_process(cmd, args, false)
	_running_pid = pid

	if pid == -1:
		_write_bridge_log(progress_path, "  ERROR: Failed to create process")
		_running_pid = -1
		return

	# Poll until process completes or cancelled
	while OS.is_process_running(pid):
		if _cancel_flag:
			_write_bridge_log(progress_path, "  CANCELLED, killing PID=%d" % pid)
			OS.kill(pid)
			_running_pid = -1
			DirAccess.remove_absolute(script_temp_path)
			if FileAccess.file_exists(progress_path):
				DirAccess.remove_absolute(progress_path)
			_write_bridge_log(progress_path, "  bridge cancelled")
			return
		OS.delay_msec(200)

	_running_pid = -1
	DirAccess.remove_absolute(script_temp_path)
	_write_bridge_log(progress_path, "  bridge done")

static func _write_bridge_log(progress_path: String, msg: String):
	var log_path := progress_path.replace("_progress.json", "_bridge.log")
	var f := FileAccess.open(log_path, FileAccess.WRITE_READ)
	if f:
		f.seek_end()
		f.store_string(msg + "\n")
		f.close()

static func _find_python() -> String:
	var o: Array = []
	if OS.execute("python", ["--version"], o, true) == 0:
		return "python"
	if OS.execute("python3", ["--version"], o, true) == 0:
		return "python3"
	return ""
